import { Client, Account, Databases } from "appwrite";

export const {
  NEXT_PUBLIC_APPWRITE_PROJECT_ID: PROJECT_ID,
  NEXT_PUBLIC_APPWRITE_API_KEY: API_KEY,
  NEXT_PUBLIC_APPWRITE_ENDPOINT: ENDPOINT,
  NEXT_PUBLIC_APPWRITE_DATABASE_ID: DATABASE_ID,
  NEXT_PUBLIC_APPWRITE_STORAGE_ID: STORAGE_ID,
  NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID: USERS_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_USERS_PROFILE_COLLECTION_ID: USERS_PROFILE_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_TRAINERS_PROFILE_COLLECTION_ID:
    TRAINERS_PROFILE_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_APPOINTMENT_COLLECTION_ID: APPOINTMENT_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_RATING_COLLECTION_ID: RATING_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_ADMIN_REQUEST_COLLECTION_ID: ADMIN_REQUEST_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_INBOX_COLLECTION_ID: INBOX_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_MESSAGE_COLLECTION_ID: MESSAGE_COLLECTION_ID,
} = process.env;

export const client = new Client();

client
  .setEndpoint(process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!)
  .setProject(process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!);

export const accounts = new Account(client);
export const databases = new Databases(client);
export { ID } from "appwrite";
